### ISSUE TITLE
Imgur image uploads

### ISSUE THREAD

**Issue by BrentMifsud** [Coding-Couch/dinnr-app#10]
Imgur's api docs here: https://apidocs.imgur.com/#intro

# Tasks
- [ ] Find a secure way of storing imgur api key
- [ ] Build an ImgurClient for uploading and deleting recipe images.
- [ ] When a recipe is deleted, all of its images should be deleted from imgur as well.
